AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  FizzBuzzApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      Handler: src/index.default
      Runtime: nodejs14.x
