name: Integration
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: "https://npm.pkg.github.com"
          scope: "@stormreply"
      - name: Install dependencies
        run: npm ci && npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Build sources
        run: npm run build:production
      - name: Lint sources
        run: npm run lint
      - name: Run tests
        run: npm test
        env:
          CI: true
      - name: SonarCloud Scan - Infrastructure
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/infrastructure
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Scan - Lambda
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: packages/lambda
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

